import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/app/components/NavBar/NavBar";
import ReactQueryProvider from '@/app/providers/ReactQueryProvider';

export const metadata: Metadata = {
  title: "Modern Walk",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavBar></NavBar>
        <ReactQueryProvider>
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
